### ISSUE TITLE
[main branch 37ed967] Failed to build chatglm-6b trt engines

### ISSUE THREAD

**Issue by Ajay-Wong** [triton-inference-server/tensorrtllm_backend#144]
I use tensorrt-llm branch[[6755a3f](https://github.com/NVIDIA/TensorRT-LLM/tree/6755a3f077bc39d51b74bbcb50403f54663cc8dc)] and triton-inference-server main branch[37ed967] to build container successfully.
But  I failed to convert chatglm-6b( https://huggingface.co/THUDM/chatglm-6b/tree/main) to trt engine, when i use this command:
python build.py --model_name chatglm_6b --world_size 1 --dtype float16 --max_batch_size 32 --max_input_len 1024 --max_output_len 1024 --max_beam_width 5 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --remove_input_padding --use_inflight_batching --use_weight_only --weight_only_precision int8 --paged_kv_cache --model_dir=/data/chatglm_6B/origin_hf_model/chatglm_6b --output_dir=./trt_engines/chatglm6b_tp1_inflight_w8a16

I received some error messages as follows.

[11/18/2023-14:13:19] [TRT-LLM] [I] Activation memory size: 36399.38 MiB
[11/18/2023-14:13:19] [TRT-LLM] [I] Weights memory size: 7424.72 MiB
[11/18/2023-14:13:19] [TRT-LLM] [I] Max KV Cache memory size: 143360.00 MiB
[11/18/2023-14:13:19] [TRT-LLM] [I] Estimated max memory usage on runtime: 187184.10 MiB
Traceback (most recent call last):
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 751, in <module>
    run_build()
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 743, in run_build
    build(0, args)
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 699, in build
    check_gpt_mem_usage(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/profiler.py", line 311, in check_gpt_mem_usage
    _, _, total_mem = device_memory_info(torch.cuda.current_device())
TypeError: cannot unpack non-iterable NoneType object

My operating environment information：
NVIDIA A800-SXM4-80GB，Driver Version: 470.161.03   CUDA Version: 12.2

**Comment by byshiue** [comment]
I try to reproduce your issue by following your steps on main branch [6755a3f](https://github.com/NVIDIA/TensorRT-LLM/tree/6755a3f077bc39d51b74bbcb50403f54663cc8dc), but fail.

Can you check the result of `torch.cuda.current_device()` and `device_memory_info(torch.cuda.current_device())`?

**Comment by byshiue** [comment]
I reproduce this issue on triton docker image, it may be environment issue, I will continue investigating.

**Comment by Ajay-Wong** [comment]
> ```shell
> pip install psutil==5.9.5 pynvml==11.5.0
> ```

I try it, but get new errors.

[11/21/2023-07:40:11] [TRT-LLM] [I] Activation memory size: 36399.38 MiB
[11/21/2023-07:40:11] [TRT-LLM] [I] Weights memory size: 7424.72 MiB
[11/21/2023-07:40:11] [TRT-LLM] [I] Max KV Cache memory size: 143360.00 MiB
[11/21/2023-07:40:11] [TRT-LLM] [I] Estimated max memory usage on runtime: 187184.10 MiB
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 850, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetMemoryInfo_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 751, in <module>
    run_build()
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 743, in run_build
    build(0, args)
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 699, in build
    check_gpt_mem_usage(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/profiler.py", line 311, in check_gpt_mem_usage
    _, _, total_mem = device_memory_info(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/profiler.py", line 253, in device_memory_info
    return _default_memory_monitor.device_memory_info(device)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/profiler.py", line 179, in device_memory_info
    mem_info = self._device_mem__fn(self.device_handles[index])
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 2438, in nvmlDeviceGetMemoryInfo
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetMemoryInfo_v2")
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 853, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found

**Comment by byshiue** [comment]
Then I suggest you delete these lines https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/profiler.py#L311-L324 directly.

**Comment by Ajay-Wong** [comment]
> Then I suggest you delete these lines https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/profiler.py#L311-L324 directly.

thanks, it works.

**Comment by byshiue** [comment]
> > Then I suggest you delete these lines https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/profiler.py#L311-L324 directly.
> 
> thanks, it works.

Thank you for the update and reporting this issue. We will fix it and update the code soon. 

Close this bug, feel free to reopen it if needed.
