### ISSUE TITLE
Compile Error : Failed to build engine for rank 0 - ( H100 llama ) 

### ISSUE THREAD

**Issue by dnda-scaler** [triton-inference-server/tensorrtllm_backend#204]
Hello,
I try to build a llama model that has been previously transformed using Hugging Face Transformers.
I rely on a prebuilt docker image based on 23.10-trtllm-python-py3.
```
 docker run                                       \
        --runtime=nvidia                                \
        --gpus all                                      \
        -it --rm                                        \
        --net host --shm-size=2g                        \
        --ulimit memlock=-1 --ulimit stack=67108864     \
        -v /scratch:/workspace                          \
        tritonserver-aipulse:23.10                      \
        python  /workspace/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py  \
        --model_dir /workspace/meta/hf-weights/7B-chat  \
        --dtype float16 \
        --use_gpt_attention_plugin float16  \
        --paged_kv_cache \
        --remove_input_padding \
        --use_gemm_plugin float16  \
        --output_dir "/workspace/trt-engines/llama_7b/fp16/1-gpu"  \
        --max_input_len 2048 --max_output_len 512 \
        --use_rmsnorm_plugin float16  \
        --enable_context_fmha \
        --use_inflight_batching
```
The command worked 2-3 weeks before and  now just after I  have updated the repository and  I have now  the following error : 
[12/11/2023-17:20:46] [TRT] [E] 9: LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0: could not find any supported formats consistent with input/output data types
[12/11/2023-17:20:46] [TRT] [E] 9: [pluginV2Builder.cpp::reportPluginError::24] Error Code 9: Internal Error (LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0: could not find any supported formats consistent with input/output data types)
[12/11/2023-17:20:46] [TRT-LLM] [E] Engine building failed, please check the error log.
[12/11/2023-17:20:46] [TRT-LLM] [I] Config saved to /workspace/trt-engines/llama_7b/fp16/1-gpu/config.json.
Traceback (most recent call last):
  File "/workspace/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 839, in <module>
    build(0, args)
  File "/workspace/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 785, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

**Comment by byshiue** [comment]
When you update the code, have you rebuild the docker image or rebuild the tensorrt_llm? 
Also, when you mention you update the code, do you update the code to the latest main branch?

**Comment by dnda-scaler** [comment]
I have clone the [tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend) repository  in its last version. 
I rely on the  Dockerfile below to get my build tritonserver image.
And after I run the build  using the build script provided in tensorrtllm_backend/tensorrt_llm/examples/llama/build.py
```
ARG TAG=23.10-trtllm-python-py3
FROM nvcr.io/nvidia/tritonserver:${TAG}

ENV DEBIAN_FRONTEND noninteractive

# Install TRT LLM
RUN pip install --no-cache-dir \
        git+https://github.com/NVIDIA/TensorRT-LLM.git

# Dependency copy
RUN mkdir /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/ && \
    cp /opt/tritonserver/backends/tensorrtllm/* /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/

RUN pip install  --no-cache-dir \
    datasets==2.14.5 \
    rouge_score~=0.1.2 \
    sentencepiece~=0.1.99

RUN mkdir -p /workspace

WORKDIR /workspace
```
