### ISSUE TITLE
Cannot import name 'LoraConfig' from 'tensorrt_llm.runtime.lora_manager'

### ISSUE THREAD

**Issue by wjueyao** [triton-inference-server/tensorrtllm_backend#209]
I build tensorrtllm_backend from main branch

```
git clone -b main  https://github.com/triton-inference-server/tensorrtllm_backend.git
# Update the submodules
cd tensorrtllm_backend
git lfs install
git submodule update --init --recursive
# Use the Dockerfile to build the backend in a container
# For x86_64
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
```

Then I try to build engines using codellama-7b

```
python3 hf_llama_convert.py -i /weights/huggingface/codellama/CodeLlama-7b-hf    \
                -o /weights/trt_llm/2023.12.12/llama_7B_int8_kv_cache \
                --calibrate-kv-cache \
                -t fp16 \
                --tensor-parallelism 4
```

```
# Build model with both INT8 weight-only and INT8 KV cache enabled
python build.py --ft_model_dir=/weights/trt_llm/2023.12.12/llama_7B_int8_kv_cache/4-gpu/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --paged_kv_cache \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --max_batch_size 64  \
                --vocab_size 32016  \
                --output_dir /weights/trt_llm/2023.12.12/convert/4-gpu \
                --int8_kv_cache \
                --use_weight_only \
                --world_size 4 \
                --tp_size 4
```

And i got the following error when running build.py

```
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 28, in <module>
    from weight import (get_scaling_factors, load_from_awq_llama, load_from_binary,
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/weight.py", line 32, in <module>
    from tensorrt_llm.runtime.lora_manager import LoraConfig
ImportError: cannot import name 'LoraConfig' from 'tensorrt_llm.runtime.lora_manager' (/app/tensorrt_llm/tensorrt_llm/runtime/lora_manager.py)
```

**Comment by byshiue** [comment]
Could you check the file of `/app/tensorrt_llm/tensorrt_llm/runtime/lora_manager.py`? Could you find `LoraConfig` in the file?

**Comment by wjueyao** [comment]
> Could you check the file of `/app/tensorrt_llm/tensorrt_llm/runtime/lora_manager.py`? Could you find `LoraConfig` in the file?

Yep. I doule-checked the file and turned out I am not using the same version of `/app/tensorrt_llm/tensorrt_llm/runtime/lora_manager.py` as the backend I built. After changing to the same version, the problem is solved now.

**Comment by byshiue** [comment]
Thank you for update. Close this bug. If you still have question/issue, feel free to ask here and we will reopen the issue.
