### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_llm'

### ISSUE THREAD

**Issue by liuao743** [triton-inference-server/tensorrtllm_backend#231]
I use tensorrt-LLM 0.6.1 generating the engine.
I use triton-server 23.10.(container nvcr.io/nvidia/tritonserver:23.10-py3)
When I use tritonserver, I get the error:
I1219 05:47:06.220452 1660 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7fe44c000000' with size 268435456
I1219 05:47:06.257990 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1219 05:47:06.258033 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
I1219 05:47:06.258051 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 2 with size 67108864
I1219 05:47:06.258060 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 3 with size 67108864
I1219 05:47:06.258083 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 4 with size 67108864
I1219 05:47:06.258098 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 5 with size 67108864
I1219 05:47:06.258106 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 6 with size 67108864
I1219 05:47:06.258113 1660 cuda_memory_manager.cc:107] CUDA memory pool is created on device 7 with size 67108864
I1219 05:47:10.506798 1660 model_lifecycle.cc:461] loading: tensorrt_llm:1
I1219 05:47:10.506856 1660 model_lifecycle.cc:461] loading: preprocessing:1
I1219 05:47:10.506876 1660 model_lifecycle.cc:461] loading: postprocessing:1
I1219 05:47:10.650040 1660 python_be.cc:1827] Input tensors can be both in CPU and GPU. FORCE_CPU_ONLY_INPUT_TENSORS is off.
I1219 05:47:13.640649 1660 python_be.cc:2199] TRITONBACKEND_ModelInstanceInitialize: postprocessing_0_0 (CPU device 0)
I1219 05:47:15.006910 1660 model_lifecycle.cc:818] successfully loaded 'postprocessing'
I1219 05:47:16.115149 1684 pb_stub.cc:257]  Failed to initialize Python stub for auto-complete: ModuleNotFoundError: No module named 'tensorrt_llm'

At:
  /models/tensorrt_llm/1/model.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load

I1219 05:47:17.983586 1660 python_be.cc:2199] TRITONBACKEND_ModelInstanceInitialize: preprocessing_0_0 (CPU device 0)
I1219 05:47:38.170125 1660 model_lifecycle.cc:818] successfully loaded 'preprocessing'

And it stuck here and can't proceed.
When I use pip to install the tensorrt_llm, I get the error:
Collecting tensorrt_llm==0.5.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/65/d2/73b872b9e7fac4ea0bee7efad1ea3c26c8c104ff7636ce2a62822b471a6e/tensorrt-llm-0.5.0.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a8zn9jxh/tensorrt-llm_4a396b45e8134909858881a63eed6b4c/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

How can I solve the problem?

**Comment by kaiyux** [comment]
Please follow https://github.com/triton-inference-server/tensorrtllm_backend/tree/main#prepare-tensorrt-llm-engines to install tensorrt-llm. Please ensure you use same version of tensorrt llm to build engine and run server.
