### ISSUE TITLE
Always shows timeout when concurrently requesting

### ISSUE THREAD

**Issue by ZihanLiao** [triton-inference-server/tensorrtllm_backend#254]
### **Problem**
As my max_batch_size is set to 16 when building the engine, I set concurrency to 16 when I do inflight_batching inference. The following timeout always occurred.

Each input token length is about 1300, and took about 10~12 seconds to finish one sample.
Seems like there is no inflight_batching took place.

`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/tritonclient/http/_client.py", line 1577, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/tritonclient/http/_client.py", line 290, in _post
    response = self._client_stub.post(
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
2023-12-25T08:50:43Z <Greenlet at 0x7fc691c22c00: wrapped_post('v2/models/ensemble/infer', b'{"id":"1","inputs":[{"name":"text_input","shape", {'Inference-Header-Content-Length': 457}, None)> failed with TimeoutError

Traceback (most recent call last):
  File "/data/liaozihan/tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py", line 265, in <module>
    test_performance(client, prompts, output_lens)
  File "/data/liaozihan/tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py", line 179, in test_performance
    results = utils.get_http_results(async_requests)
  File "/data/liaozihan/tensorrtllm_backend/tools/utils/utils.py", line 139, in get_http_results
    results.append(async_request.get_result())
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/tritonclient/http/_client.py", line 92, in get_result
    response = self._greenlet.get(block=block, timeout=timeout)
  File "src/gevent/greenlet.py", line 831, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 373, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/gevent/_compat.py", line 49, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/tritonclient/http/_client.py", line 1577, in wrapped_post
    return self._post(request_uri, request_body, headers, query_params)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/tritonclient/http/_client.py", line 290, in _post
    response = self._client_stub.post(
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 292, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 164, in __init__
    self._read_headers()
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/geventhttpclient/response.py", line 184, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/home/liaozihan/anaconda3/envs/myniche/lib/python3.10/site-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out`

### **Building scripts**
`python build.py --model_dir ./mistral_7b_finetune_lora_merged \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --paged_kv_cache \
                --output_dir ./mistral_7b_finetune_lora_merged/trt_engines/weight_only/1-gpu \
                --max_input_len 4096 \
                --max_output_len 4096 \
                --max_batch_size 16 \
                --use_inflight_batching \
                --use_weight_only \
                --int8_kv_cache \
                --multi_block_mode `

### **Model**
Mistral-7b with int8 weight-only quantization and merged LORA plugin.

### **Environment**
NVIDIA A800 80GB PCIe
tensorrt_llm:0.6.1

**Comment by juney-nvidia** [comment]
@ZihanLiao 

Hi,

Thanks for reporting this. Can you also help follow [this](https://github.com/triton-inference-server/tensorrtllm_backend/issues/270) template to provide the concrete steps of starting the Triton backend and client?

It can ease the efforts of our investigation.

June

**Comment by handoku** [comment]
using grpc protocol can avoid this problem

**Comment by ZihanLiao** [comment]
> using grpc protocol can avoid this problem

Thx! Service ran stably with grpc.
