### ISSUE TITLE
Git LFS error while building docker

### ISSUE THREAD

**Issue by amir1m** [triton-inference-server/tensorrtllm_backend#302]
Hello,
I have base Ubuntu 22.04 VM with two A10 GPUs (Driver Version: 545.23.08    CUDA Version: 12.3 ). 

I am trying to build the backend docker using command

`sudo docker build  -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .`

However, getting following error message:

```
;-gencode;arch=compute_90,code=sm_90
CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:337 (find_package)


-- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so  
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0
-- Building for TensorRT version: 9.2.0, library version: 9
-- Using MPI_C_INCLUDE_DIRS: /opt/hpcx/ompi/include;/opt/hpcx/ompi/include/openmpi;/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include
-- Using MPI_C_LIBRARIES: /opt/hpcx/ompi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Operating System: ubuntu, 22.04
CMake Error at tensorrt_llm/CMakeLists.txt:105 (message):
  The batch manager library is truncated or incomplete.  This is usually
  caused by using Git LFS (Large File Storage) incorrectly.  Please try
  running command `git lfs install && git lfs pull`.


-- Configuring incomplete, errors occurred!
See also "/app/tensorrt_llm/cpp/build/CMakeFiles/CMakeOutput.log".
See also "/app/tensorrt_llm/cpp/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/app/tensorrt_llm/scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/app/tensorrt_llm/scripts/build_wheel.py", line 160, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="ON"  -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include  -S "/app/tensorrt_llm/cpp"' returned non-zero exit status 1.
The command '/bin/sh -c cd tensorrt_llm && python3 scripts/build_wheel.py --trt_root="${TRT_ROOT}" -i -c && cd ..' returned a non-zero code: 1

```

Can someone please help?

Thanks.

**Comment by byshiue** [comment]
Please try running
```bash
git-lfs pull
``` 
and rebuild the docker image again.

**Comment by amir1m** [comment]
Thanks @byshiue for your response!
Tried git-lfs full but still faced the same issue.

Then, tried with TensorRT LLM repository to create the TRT Engine (which was working for me last month) but faced error while converting HF weights to RT-LLM https://github.com/NVIDIA/TensorRT-LLM/issues/902 :

```
root@myhostname-release:/code/tensorrt_llm/examples/falcon#python3 convert_checkpoint.py --model_dir ./merged/ --dtype bfloat16 --output_dir ./trt_ckpt/bf16/1-gpu/
0.7.1
[01/17/2024-13:10:40] 
WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.98it/s]
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/falcon/convert_checkpoint.py", line 1120, in <module>
    covert_and_save(rank)
  File "/code/tensorrt_llm/examples/falcon/convert_checkpoint.py", line 1097, in covert_and_save
    weights = convert_hf_falcon(
  File "/code/tensorrt_llm/examples/falcon/convert_checkpoint.py", line 379, in convert_hf_falcon
    qkv_w = split_qkv_weight(qkv_weight,
  File "/code/tensorrt_llm/examples/falcon/convert_checkpoint.py", line 265, in split_qkv_weight
    weight = reorder_qkv_weight_or_bias(weight,
  File "/code/tensorrt_llm/examples/falcon/convert_checkpoint.py", line 214, in reorder_qkv_weight_or_bias
    assert weight.shape[0] == num_kv_heads * num_group_heads * head_dim, \
AssertionError: 4672 != 71 * 3 * 64
```

**Comment by byshiue** [comment]
I don't really get your point. If you still have same issue, how do you run `convert_checkpoint.py`? 

Also, do you run `git-lfs pull` in `tensorrtllm_backend` or `tensorrt_llm`? If you run in the former, please try in the later again.
