### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'StatusCode'

### ISSUE THREAD

**Issue by lyc728** [triton-inference-server/tensorrtllm_backend#317]
Input: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
写一篇具有现代化诗意的作文<|im_end|>
<|im_start|>assistant

Output beam 0: 在现代化的今天，我们面临着许多挑战，但也有许多机会。我们可以利用这些机会，去探索未知，去发现新的可能性，去创造一个更加美好的未来。我们可以把我们的梦想变成现实，把我们的希望变成现实，把我们的梦想变成现实。我们可以把我们的梦想变成现实，把我们的希望变成现实，把我们的梦想变成现实。我们可以把我们的梦想变成现实，把我们的希望变成现实，把我们的梦想变成现实。我们可以把我们的梦想变成现实，
Exception ignored in: <function InferenceServerClient.__del__ at 0x7f25dc0e9c60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'

when the result coming ,An error message was reported

**Comment by byshiue** [comment]
There is same issue here https://github.com/triton-inference-server/tensorrtllm_backend/issues/285. Mark this one as duplicated and close.
