### ISSUE TITLE
Example of LoRa weights

### ISSUE THREAD

**Issue by TheCodeWrangler** [triton-inference-server/tensorrtllm_backend#399]
I would like to send Lora weights through to a compiled tensor rt llm model but am unsure how to load the .bin weights and pass them to Triton.   An example of using them and passing in weights would be very helpful

**Comment by byshiue** [comment]
Here is example https://github.com/triton-inference-server/tensorrtllm_backend/tree/main/inflight_batcher_llm#running-lora-inference-with-inflight-batching

**Comment by TheCodeWrangler** [comment]
Thank you for pointing me to this!  Things that this helped clear up (and may help someone in the future).

Starting with .safetensors from hugingface you need to convert them to .bin adaptors

```
import torch
from safetensors.torch import load_file

torch.save(load_file("adapter_model.safetensors"), "adapter_model.bin")`
```

Then you need to convert that into and `.npy` format by using the [`examples/hf_lora_convert.py`](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/hf_lora_convert.py)

Is it possible to use "bfloat16" adaptor weights?

I ran into issues when attempting to use my adaptors which were compiled for bfloat16

Running:

```bash
python3 hf_lora_convert.py \
        -o ${LOCAL_COMPILED_WEIGHTS}/lora/0 \
        -i ${LORA_DIR_1} \
        --storage-type bfloat16 \
        --verbose
 ```
 
 Results inthe following error

```bash
    main(args)
  File "/code/hf_lora_convert.py", line 141, in main
    convert_hf_model(args.in_file, args.storage_type, args.out_dir)
  File "/code/hf_lora_convert.py", line 122, in convert_hf_model
    dim=0).unsqueeze(0).to(dtype=str_dtype_to_torch(dtype)).cpu().numpy()
TypeError: Got unsupported ScalarType BFloat16
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024032600
Traceback (most recent call last):
  File "/code/hf_lora_convert.py", line 176, in <module>

```

I went ahead and converted to float32 instead just to continue testing (and hoping that precision was maintained)

....

Then in triton-inference-server I noticed that the expected model weights format is [FP16](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L241)

When I load the models and configs and send them to the backend (which was compiled for bfloat16) 

After calling in triton-inference-server i get the following error

```bash
[TensorRT-LLM][ERROR] Assertion failed: Expected lora weights to be the same data type as base model (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/loraUtils.cpp:66)
```

Is there any way for me to pass in the adaptor weights as bfloat16?

I noticed that TYPE_BF16 is listed [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html#datatypes)

But it does not seem like `pb_utils.triton_string_to_numpy("TYPE_BF16")` is able to use it (since numpy does not have bfloat16)
