### ISSUE TITLE
Error when Building the TensorRT-LLM Backend with Option 3.

### ISSUE THREAD

**Issue by dongluw** [triton-inference-server/tensorrtllm_backend#44]
Hi,

I ran into error when building the TensorRT-LLM backend with Option 3. at step ` [trt_llm_builder 4/4] `, any idea what could be the problem?

```
...

 => [trt_llm_builder 3/4] COPY tensorrt_llm tensorrt_llm                   1.7s
 => ERROR [trt_llm_builder 4/4] RUN cd tensorrt_llm && python3 scripts  3747.2s
------
 > [trt_llm_builder 4/4] RUN cd tensorrt_llm && python3 scripts/build_wheel.py --trt_root="/usr/local/tensorrt" -i -c && cd ..:
#22 0.962 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com

...

#22 3746.9 [100%] Linking CXX shared library libtensorrt_llm.so
#22 3747.1 /usr/bin/ld:/app/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.pre_cxx11.a: file format not recognized; treating as linker script
#22 3747.1 /usr/bin/ld:/app/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.pre_cxx11.a:1: syntax error
#22 3747.1 collect2: error: ld returned 1 exit status
#22 3747.1 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
#22 3747.1 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
#22 3747.1 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
#22 3747.1 gmake: *** [Makefile:179: tensorrt_llm] Error 2
#22 3747.1 Traceback (most recent call last):
#22 3747.1   File "/app/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
#22 3747.1     main(**vars(args))
#22 3747.1   File "/app/tensorrt_llm/scripts/build_wheel.py", line 152, in main
#22 3747.1     build_run(
#22 3747.1   File "/usr/lib/python3.10/subprocess.py", line 526, in run
#22 3747.1     raise CalledProcessError(retcode, process.args,
#22 3747.1 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 24 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
executor failed running [/bin/sh -c cd tensorrt_llm && python3 scripts/build_wheel.py --trt_root="${TRT_ROOT}" -i -c && cd ..]: exit code: 1
```

**Comment by byshiue** [comment]
It looks you don't clone `libtensorrt_llm_batch_manager_static.pre_cxx11.a` correctly. It is a lfs file and you need to  install `git-lfs`. Can you try running 
```bash
cd tensorrt_llm
sudo apt-get install git-lfs
git-lfs pull
```
and build again?

**Comment by dongluw** [comment]
thank you @byshiue that worked!

**Comment by byshiue** [comment]
Thank you for update. Close this issue.
