### ISSUE TITLE
How to correctly obtain streaming output from Triton using gRPC?

### ISSUE THREAD

**Issue by whalefa1I** [triton-inference-server/tensorrtllm_backend#51]
I am using the Triton 23.08 image, and I can get the correct response from the HTTP client, as well as a complete response from the gRPC client. However, I would like to know if it is possible to obtain streaming output while having both decoupled and inflight_fused_batching enabled at the same time? I used my own gRPC streaming client and encountered the following error in Java:
```
io.grpc.StatusRuntimeException: UNIMPLEMENTED: ModelInfer RPC doesn't support models with decoupled transaction policy
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Alternatively, could you provide an example of how to correctly obtain a streaming response in Java?

**Comment by karthiknayak02** [comment]
Seems like you might have to try ModelStreamInfer RPC
https://github.com/triton-inference-server/common/blob/adef772f65153ef28619cf9405c08198910f2640/protobuf/grpc_service.proto#L77C1-L92C4
